spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - 'http://15.164.81.45:8080'
            allowCredentials: true   # 카멜케이스 주의
            allowedHeaders: '*'      # 모든 헤더 허용
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

server:
  port: 8080
